language: python
python:
    - "3.5"
node_js: "stable"
before_install:
    - npm install -g npm@latest
install:
    - pip install html-linter
    - npm install -g jshint
    - npm install -g stylelint
script:
    - html_lint.py *.html --config .htmllintrc.json
    - jshint ./js/*.js --config .jshint
    - stylelint "css/*.css" --config .stylelintrc.json